apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/boommb92-svg/bluegreen-app.git
    path: 'app-chart'
    targetRevision: HEAD
    helm:
      values: |
        activeColor: "blue"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
